# Names of the SLMs we want to use
slm_models_names: []
# Names of the LLM we want to test them against
llm_model_name: ""
# Name of the datasets we want to test them on
datasets_names: []
# Folder to all the datasets
output_folder: ""
# Save the vector index of the dataset per model
save_index: False
